spring:
  h2:
    console:
      enabled: true
  datasource:
    url : jdbc:h2:mem:test
    username : sa
    password :
    driver-class-name: org.h2.Driver

  jpa:
    ddl-auto : create-drop
    properties:
      hibernate:
        show_sql : true
        format_aql : true


logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.internalutil: info
    org.hibernate.type.descriptor.sql.BasicExtractor: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.engine.transaction.internal.TransactionImpl: trace
